### ISSUE TITLE
How to run code after logging out?

### ISSUE THREAD

**Issue by biona001** [Hua-Zhou/aw-area51#1]
I have some scripts that potentially need >24 hours to run in Julia. Is there a way to run them without constantly being connected via ssh?

**Comment by Hua-Zhou** [comment]
Dear Ben,

You can use `nohup` or `screen` utilities in Linux. See my 203B lecture
notes.
https://ucla-biostat203b-2020winter.github.io/slides/02-linux/linux.html#run-long-jobs

Best,

Hua
